server:
 port: 8081
 servlet:
  context-path: /api  
spring:
 jpa:
  hibernate:
   ddl-auto: update
 datasource:
  url: jdbc:postgresql://localhost:5432/db-spring-security
  username: postgres
  password: admin
  driver-class-name: org.postgresql.Driver